### ISSUE TITLE
broom::tidy method for msm models

### ISSUE THREAD

**Issue by larmarange** [chjackson/msm#13]
Hello,

thanks a lot for your package. Did you ever consider providing tidiers for msm models, allowing to easy use the results for producing graphs or table?

It would be great to have a `tidy` method for msm models. cf. https://broom.tidyverse.org/articles/external-tidiers.html

Ideally, there should be an option to precise that should be returned:

1. a data frame of all hazard ratios (one row per HR)
2. a data frame of all prevalence (one row per status and per time)

**Comment by larmarange** [comment]
In case it could be useful for watching what could be the result of some tidiers for `msm`, a draft of very basic tidiers could be found at https://github.com/larmarange/JLutils/blob/master/R/tidy_msm.R

Best regards

**Comment by chjackson** [comment]
I think this would be a great addition, but adding new features to msm is low priority for me at the moment.  So I'd encourage others to write these, as you have done, especially since a feature like this doesn't need to know msm internals.  I'll make a note to test out what you've written - I've not used broom myself, but I like tidyverse stuff.

**Comment by chjackson** [comment]
Tidying methods for msm and most msm output functions now implemented in https://github.com/chjackson/msm/commit/00c7a7190246cd695d205bedf47d11169890bd86 .   For tidy hazard ratios, just call `tidy()` on the `msm` output, rather than the output of `hazard.msm` - both log HRs and HRs are presented.
