### ISSUE TITLE
Error in Pmat[x[1], x[2]] : out of bounds

### ISSUE THREAD

**Issue by agm75** [chjackson/msm#56]
Dear Dr. Jackson,

I am currently trying to fit a model using the msm() command and stand stumbled upon an error: 

**Error in Pmat[x[1], x[2]] : out of bounds**

I fitted a similar model on a previous dataset and it was working fine. I searched for the error message in the [msm() code](https://github.com/cran/msm/blob/master/R/msm.R) but without success.  

My code looks like this : 

```
msm_model <- msm(data = database,
                 subject = id,
                 formula = state ~ age, 
                 covariates = list("1-2" = ~ sex + education,
                                   "1-3" = ~ sex + education + age,
                                   "1-4" = ~ sex + education,
                                   "2-1" = ~ sex + education,
                                   "2-3" = ~ sex + education + age,
                                   "2-4" = ~ sex + education,
                                   "3-4" = ~ sex + education),
                 qmatrix = trans_mat,
                 exacttimes = F,
                 deathexact = c(4),
                 control=list(fnscale = 37000),
                 gen.inits = T
                 )
msm_model
```
Any idea where the problem lies? 

Thank for your help.

**Comment by chjackson** [comment]
Could you make the example fully reproducible please, with simulated data if necessary?   I guess it's something to do with the specific data or qmatrix, but hard to tell without seeing those.

**Comment by chjackson** [comment]
There was a bug in msm which affects autogeneration of initial values when the state variable is supplied as a factor - this is fixed in https://github.com/chjackson/msm/commit/13ebafe940a5cf43af5fdd9b3a4fe248538366ce .  Factor state variables are supported, as long as the levels are labelled `"1","2",` etc., as they are in your data. 

You can work around this bug without updating the package, by storing the state variable as numeric, or by supplying your own initial values instead of using `gen.inits`. 

A warning about the specific model that you have defined here - you are using intermittently observed data, and allowing instantaneous jumps from state 1 to state 3.  If the states represent ordered categories, such as severity of a disease, this shouldn't be allowed in continuous time.  The structure of the qmatrix should not be specified based on the `statetable.msm` output, which describes transitions over an interval rather than instantaneous transitions in continuous time.    

See. e.g. the [course notes](https://chjackson.github.io/msm/msmcourse/) for more model building advice.

**Comment by agm75** [comment]
After changing the type to numeric, it worked fine.

```{r loading_data, echo = T}

# Loading the data
setwd("C:/path")
data <- read.csv2(file = "reproducible_example.csv")

# Changing type of columns of columns
data <- data %>%
  dplyr::mutate(
    
    id         = as.factor(id),
    sex        = as.factor(sex),
    education  = as.factor(education),
    state      = as.factor(state), # /!\ /!\ /!\ it should be as.numeric(), this was the issue
    
    age        = as.numeric(age),
    age_dim    = as.numeric(age_dim) # age divided by 10
  )


# Order data
data <- data[order(data$id, data$age),]
statetable.msm(data = data, state = state, subject = id)

# Matrix
trans_mat <- rbind(c(0.1, 0.1, 0.1, 0.1), 
                   c(0.1, 0.1, 0.1, 0.1), 
                   c(0  , 0  , 0.1, 0.1),
                   c(0  , 0  , 0  , 0  )
                   )

# MSM Model
msm_model <- msm(data = data,
                 subject = id,
                 formula = state ~ age_dim, 
                 covariates = list("1-2" = ~ sex + education,
                                   "1-3" = ~ sex + education + age_dim,
                                   "1-4" = ~ sex + education,
                                   "2-1" = ~ sex + education,
                                   "2-3" = ~ sex + education + age_dim,
                                   "2-4" = ~ sex + education,
                                   "3-4" = ~ sex + education),
                 qmatrix = trans_mat,
                 exacttimes = F,
                 deathexact = c(4),
                 control=list(fnscale = 37000),
                 gen.inits = T
                 )
msm_model
```

Thank you ever so much for your help Dr. Jackson!

[reproducible_example.csv](https://github.com/chjackson/msm/files/8638703/reproducible_example.csv)
