### ISSUE TITLE
continuous-time vs. discrete-time models

### ISSUE THREAD

**Issue by axinaxia** [chjackson/msm#57]
Hi Dr.Jackson,

I read your answer to the previous issue, "numerical overflow in calculating likelihood #5". If I understand correctly, if we specify "exacttimes=T", we fit discrete-time models. I wonder, in practice, when a continuous-time model should be used and when a discrete-time model should be used? Should the time interval between two observations not be too long to be able to fit a continuous-time model?

Thanks a lot!

Xin

**Comment by chjackson** [comment]
That is a misinterpretation of my comment.   `msm` always fits continuous time models.   It always assumes there is a continuous-time process underlying the data, controlled by transition intensities.  You can define transition probabilities over any discrete time interval as a function of intensities.  

`exacttimes=TRUE` means that the data represent the completely-observed transition times of the process, rather than 
 observations of the state at arbitrary times.   So if your data were equally spaced in time, you could fit a model with `exacttimes=TRUE`, and interpret the transition probabilities under that model as the transition matrix of a discrete-time model.   But if you want to fit a discrete-time model, it's better to use a tool designed for that, e.g. multinomial logistic regression.

**Comment by axinaxia** [comment]
Hi Dr.Jackson,

Thanks a lot for your explanations! 

I have another question: I am modeling a four-state model (healthy, prodromal phase of dementia, and dementia) with "msm". In my data, people have pre-scheduled examinations, therefore it is more reasonable to assume what we observed are snapshots of an ongoing process (exacttimes=F). However, in our data, some people were healthy at first but were diagnosed with dementia at the next time point. In theory, people should always experience the prodromal phase of dementia before developing dementia. Is this what you wrote as "interval transition" as opposed to "instantaneous transition"?

In this case, is it better to specify the initial value of the transition from healthy to dementia as 0?

Xin

**Comment by chjackson** [comment]
That's correct - the intensity for this transition should be assumed to be zero if it is impossible in theory in real time.
