### ISSUE TITLE
Any thoughts on adding fraility/multi level models?

### ISSUE THREAD

**Issue by adrose** [chjackson/msm#78]
Hi,

As the title states, just curious if there is any plans on adding multilevel models to the msm package?

Best,
Adon

**Comment by chjackson** [comment]
There's no plans to add this to msm.   If I were to need this kind of model for intermittently-observed data, I'd use something like [Stan](http://mc-stan.org) which has a matrix exponential function / differential equation solvers that could be used for computing the necessary likelihood.  I don't know of any worked example of doing this though. 

For continuously-observed data, a good starting point might be [frailtypack](https://cran.r-project.org/web/packages/frailtypack/index.html) - in theory, parametric survival models can be pieced together to give a multi-state model (as in [flexsurv](http://chjackson.github.io/flexsurv/)).  

Frailties can be problematic in multistate models because correlation within individuals can be hard to distinguish from dependence on the transition history (failure of the Markov assumption). [See this paper](https://link.springer.com/article/10.1007/s12561-013-9087-8).

**Comment by adrose** [comment]
Thanks @chjackson!
