### ISSUE TITLE
prevalence.msm censtime question

### ISSUE THREAD

**Issue by slee-101** [chjackson/msm#94]
Hi, thank you for this incredible work. I am new to R and msm and have been going through your vignettes / tutorials. With censtime, my understanding is if you have an absorbing state such as death and it occurs before censtime, then that value would be removed from  the prevalence data for times after censtime. 

Using the psor data set, I have tried using censtime with default (Inf), 10, and 30. The values of state 4 seem to stay constant with the total just prior to the censtime value. For instance, with censtime =10, state 4 = 8 for times >= 10 and for censtime = 30, this equals 57 times >= 30. I would have expected state4 totals to decrease after reaching censtime. Is my interpretation of this correct or does censtime only exclude values that occur after? 

I will try creating an array of censtime for subject specific values later, but I wanted to ensure appropriate understanding before continuing.

![censtime_psor_Inf_10_30](https://github.com/chjackson/msm/assets/76982219/1006bf5a-ab32-4a1a-9abc-2f4d31366312)

**Comment by chjackson** [comment]
It's not clear why you'd expect the state 4 totals to decrease after reaching `censtime`?   The constant value you see is the number of people who have died before `censtime`.  Those who die after `censtime` don't get added to this total, but we don't "forget about" the people whose deaths we have observed under the assumed observation scheme.   Is there a sentence in the help file with a misleading wording?

**Comment by slee-101** [comment]
Thank you for the explanation. In this document on page 34 is where I am confused. If a patient dies at time point 20 and would only follow up to time point 30 if alive, how would we "forget" about this death at t=30?

https://cran.r-project.org/web/packages/msm/vignettes/msm-manual.pdf





Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chjackson** [comment]
Deaths for people in the data who die after censtime are not included in the counts of death after censtime.  However deaths before censtime are included in the counts of deaths both before and after censtime.  So the count can't go up, but it can't go down either.  If a person dies before their censtime, we don't exclude them from the count after censtime, because we are trying to imitate how a similar dataset might be observed in real life - if we observed that a person died before the end of the study we would know they are dead forever.

**Comment by slee-101** [comment]
Got it. Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
