### ISSUE TITLE
How does MSM handle missing covariate data?

### ISSUE THREAD

**Issue by nickyd41** [chjackson/msm#97]
Hi Dr. Jackson,
Can you explain or point me to documentation about the handling of missing covariate data in the MSM package?  I ran a model recently that had some missing covariate data, and when I compared it with another model using complete cases only, the estimates were slightly different. Initially, I assumed this meant the model was using all available data, but just want to confirm whether my assumption is correct. 

Thank you!
Nicky

**Comment by chjackson** [comment]
See [`help(msm)`](https://chjackson.github.io/msm/reference/msm.html), argument `"na.action"`.   It uses all available data, basically.  The definition of this is subtle though.  If the last covariate value for a subject is `NA`, this record isn't dropped, because the covariate value would not have contributed to the model if it had been observed.  In msm, the probability of transition over an interval of time is assumed to depend on the covariate value at the start of the interval, not the value at the end.
